//! Chat SpacetimeDB Module
//!
//! Tables and reducers for the chat module.
//! Generated by Nexus Terminal MODULE scaffolder.
//!
//! Security infrastructure included by default:
//!   - Identity links (user_identity_links table)
//!   - Auth helpers (sender_hex, get_caller_user_id, register_identity_link)
//!   - RLS filter for identity links
//!   - Reducer auth guards on all write operations

use spacetimedb::{client_visibility_filter, CaseConversionPolicy, Filter};

pub mod tables;
pub mod reducers;
pub mod utils;

// Re-export timestamp_ms from utils/time.rs for short `crate::timestamp_ms` imports.
pub use utils::time::timestamp_ms;

// ============================================================================
// SpacetimeDB 2.0 Settings
// ============================================================================
// Preserve original Rust field/table names (no automatic snake_case → camelCase).
#[spacetimedb::settings]
const CASE_CONVERSION_POLICY: CaseConversionPolicy = CaseConversionPolicy::None;

// ============================================================================
// Row-Level Security (RLS) Filters
// ============================================================================

// Identity links: each client sees only their own link
#[client_visibility_filter]
const IDENTITY_LINK_FILTER: Filter = Filter::Sql(
    "SELECT * FROM user_identity_links WHERE user_identity_links.stdb_identity = :sender"
);
