//! Chat Reducers
//!
//! All SpacetimeDB reducer definitions for the chat module.

pub mod auth;
pub mod lifecycle;
pub mod users;
pub mod rooms;
pub mod messages;
pub mod typing;
pub mod reactions;
pub mod read_tracking;
pub mod scheduling;
pub mod permissions;
pub mod private_rooms;
pub mod drafts;
pub mod ephemeral;
pub mod servers;
pub mod categories;
pub mod roles;
pub mod channel_overrides;
pub mod emojis;
pub mod stickers;
pub mod attachments;
pub mod pins;
pub mod polls;
pub mod invites;
pub mod audit_log;
pub mod profiles;
pub mod notifications;
pub mod timeouts;
pub mod auto_mod;
pub mod bookmarks;
pub mod forums;
pub mod starred;
pub mod threads;
pub mod webhooks;
pub mod blocks;
pub mod agents;
pub mod agent_config;
pub mod system;
pub mod bot_placement;
pub mod user_bus;

// shadowing-stork — TeV reduction via room-scoped shadow index tables
pub mod shadow_index_backfill;

// Re-export reducer functions
pub use auth::*;
pub use lifecycle::*;
pub use users::*;
pub use rooms::*;
pub use messages::*;
pub use typing::*;
pub use reactions::*;
pub use read_tracking::*;
pub use scheduling::*;
pub use permissions::*;
pub use private_rooms::*;
pub use drafts::*;
pub use ephemeral::*;
pub use servers::*;
pub use categories::*;
pub use roles::*;
pub use channel_overrides::*;
pub use emojis::*;
pub use stickers::*;
pub use attachments::*;
pub use pins::*;
pub use polls::*;
pub use invites::*;
pub use audit_log::*;
pub use profiles::*;
pub use notifications::*;
pub use timeouts::*;
pub use auto_mod::*;
pub use bookmarks::*;
pub use forums::*;
pub use starred::*;
pub use threads::*;
pub use webhooks::*;
pub use blocks::*;
pub use agents::*;
pub use agent_config::*;
pub use system::*;
pub use bot_placement::*;
pub use user_bus::*;
pub use shadow_index_backfill::*;
